<a href="https://colab.research.google.com/github/Kurt30/Linear-Algebra-58020/blob/main/Practical%20Lab%20Exam%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROBLEM 1**

In [ ]:
#numpy
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
print(W)
print()
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(X)
print()
Y = np.array([[1,2,0],[0,-1,2]])
print(Y)
print()
Z = np.array([[0,1],[2,3]])
print(Z)
print()
dot = np.dot(W,Y)
print(dot)
print()
print(Z+Z)
print()
dot = np.dot(3,X)
print(dot)
print()

[[ 1 -3]
 [ 2 -2]
 [ 3  1]]

[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

[[ 1  2  0]
 [ 0 -1  2]]

[[0 1]
 [2 3]]

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]

[[0 2]
 [4 6]]

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]



**PROBLEM 2**

In [1]:
W = [[1, -3],
[2, -2],
[3, 1]]

X = [[3, 2, 1],
[-1, 2, 3],
[2, -1, 1]]

Y = [[1, 2, 0],
[0, -1, 2]]

Z = [[0, 1],
[2, 3]]

YW = [[0, 0],
[0, 0]]


YWSQUARE = [[0, 0],
[0, 0]]
for i in range(len(Y)):
    for j in range(len(W[0])):
        for k in range(len(W)):
            YW[i][j] += Y[i][k] * W[k][j]
            print('(YW)^2 matrix:')
for i in range(len(YW)):
    for j in range(len(YW[0])):
        for k in range(len(YW)):
            YWSQUARE[i][j] += YW[i][k] * YW[k][j]

for result in YWSQUARE:
        print(result)

WY = [[0, 0, 0],
[0, 0, 0],
[0, 0, 0]]


for i in range(len(W)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
             WY[i][j] += W[i][k] * Y[k][j]


WY_MINUS_X = [[0, 0, 0],
[0, 0, 0],
[0, 0, 0]]


for i in range(len(WY)):
    for j in range(len(WY[0])):
        WY_MINUS_X[i][j] = WY[i][j] - X[i][j]
        print('\nWY-X matrix:')

for result in WY_MINUS_X:
    print(result)

ZWSQUARE = [[0, 0],
[0, 0]]

for i in range(len(Z)):
    for j in range(len(Z[0])):
        for k in range(len(Z)):
            Z[i][j] += Z[i][k] * Z[k][j]


YW_MINUS_ZSQUARE = [[0, 0],
[0, 0]]

for i in range(len(YW)):
    for j in range(len(YW[0])):
        YW_MINUS_ZSQUARE[i][j] += WY[i][j] - X[i][j]

        print('\nYW-Z^2 matrix:')
for result in YW_MINUS_ZSQUARE:
    print(result)

(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
(YW)^2 matrix:
[-3, -63]
[36, -12]

WY-X matrix:

WY-X matrix:

WY-X matrix:

WY-X matrix:

WY-X matrix:

WY-X matrix:

WY-X matrix:

WY-X matrix:

WY-X matrix:
[-2, 3, -7]
[3, 4, -7]
[1, 6, 1]

YW-Z^2 matrix:

YW-Z^2 matrix:

YW-Z^2 matrix:

YW-Z^2 matrix:
[-2, 3]
[3, 4]


**B IS THE CORRECT ANSWER**